name: Workshop workflow
on: [push]

permissions: {}

jobs:
  build:
    permissions:
      contents: write
    name: Add Colab links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Add/update badges
        id: badges
        uses: trsvchn/colab-badge-action@8f705b0228595bdaa07042795e0f5d57deda2d49  # v4
        with:
          check: 'all'
          update: true
          target_branch: main
          target_repository: huggingface/workshops

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d  # v7.2.0
        with:
          commit_message: Add/update Colab badges