name: Workshop workflow
on: [push]

jobs:
  build:
    name: Add Colab links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Add/update badges
        id: badges
        uses: trsvchn/colab-badge-action@8f705b0228595bdaa07042795e0f5d57deda2d49  # v4
        with:
          check: 'all'
          update: true
          target_branch: main
          target_repository: huggingface/workshops

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a  # v4
        with:
          commit_message: Add/update Colab badges